#!/usr/bin/php
<?php

/**
 * Console Bootstrap (Release mode)
 */

require_once(dirname(__FILE__) . '/../source/framework_app/lib/boot.php');

$configuration = new lcConsoleConfiguration(realpath(dirname(__FILE__) . '/../source/framework_app/'), new lcFrameworkConfiguration());
$configuration->setIsDebugging(false);
lcApp::bootstrap($configuration)->dispatch();
