#!/usr/bin/php
<?php

/*
 * Lightcast - A Complete MVC/PHP/XSLT based Framework
 * Copyright (C) 2005-2008 Nimasystems Ltd
 *
 * This program is NOT free software; you cannot redistribute and/or modify
 * it's sources under any circumstances without the explicit knowledge and
 * agreement of the rightful owner of the software - Nimasystems Ltd.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.  See the LICENSE.txt file for more information.
 *
 * You should have received a copy of LICENSE.txt file along with this
 * program; if not, write to:
 * NIMASYSTEMS LTD
 * Plovdiv, Bulgaria
 * ZIP Code: 4000
 * Address: 95 "Kapitan Raycho" Str.
 * General E-Mail: info@nimasystems.com
 */

/**
 * Console Bootstrap
 * @package File Category
 * @subpackage File Subcategory
 * @author Nimasystems Ltd <support@nimasystems.com>
 * @version $Revision: 1458 $
 */

require_once(dirname(__FILE__) . '/../lib/boot.php');

$configuration = new lcConsoleConfiguration(realpath(dirname(__FILE__) . '/../'), new ProjectConfiguration());

@include_once('../config/boot_config.php');

$configuration->setIsDebugging(true);
lcApp::bootstrap($configuration)->dispatch();

